const ru = {
  "Terminate contract": "Расторгнуть договора",
	"High price": "Высокая цена",
	"Disruptions lack of internet": "Срывы отсутствие интернета",
	"Low speed": "Низкая скорость",
	"Moving": "Переезд",
	"Bad service": "Плохой сервис",
	"Lack of required service": "Отсутствие необходимой услуги",
	"Do not use": "Не пользуюсь",
	"PINFL": "ПИНФЛ",
	"Termination_reason": "Расторжение договора в связи с нижеуказанными причинами",
	"Shutdown date": "Дата отключения",
	"Return Form": "Форма возврата",
	"Refund_balance": "Прошу вернуть мне остаток средств",
	"FIO": "Ф.И.О.",
	"Name_bank":"Название Банка",
	"Num_card": "Номер карты",
	"ACC_bank": "Расчетный счет банка",
	"INN_bank": "ИНН банка",
	"MFO_bank": "МФО банка",
	"Form_return_terminal": "Форму по возврату абонентом терминала компании",
	"Type_return_terminal1": "обязуюсь вернуть терминал",
	"Type_return_terminal2": "обязуюсь вернуть деньги за терминал",
	"Return_contract_num": "Контактный номер для возврата",
	"Access denied": "В доступе отказано"
};

const uz = {
	"Terminate contract": "Shartnomalarni bekor qilish",
	"High price": "Narxlar yuqori",
	"Disruptions lack of internet": "Internet yetishmasligi",
	"Low speed": "Past tezlik",
	"Moving": "Ko'chib ketish",
	"Bad service": "Yomon xizmat",
	"Lack of required service": "Kerakli xizmat yo'qligi",
	"Do not use": "Foydalanmayman",
	"PINFL": "PINFL",
	"Termination_reason": "Shartnomani quyidagi sabablarga ko'ra bekor qilish",
	"Shutdown date": "O'chirish sanasi",
	"Return Form": "Mablag'ni qaytarish formasi",
	"Refund_balance": "Qaytarish summasi",
	"FIO": "F.I.SH",
	"Name_bank":"Bank nomi",
	"Num_card": "Karta raqami",
	"ACC_bank": "Bank hisob raqami",
	"INN_bank": "Bank INN",
	"MFO_bank": "Bank MFO",
	"Form_return_terminal": "Kompaniya terminalini abonent tomonidan qaytarish formasi",
	"Type_return_terminal1": "Terminalni qaytarib berishga majburman",
	"Type_return_terminal2": "Terminal uchun pulni qaytarishga majburman",
	"Return_contract_num": "Bog'lanish uchun telefon raqami",
	"Access denied": "Ruxsat yo'q"

};

export default { ru, uz };
