import {Color} from '@app/colors';
import {createTheme} from '@app/helpers/create-theme';

export const styles = createTheme({
  wrapper: {
    padding: 20,
  },
  title: {
    width: '100%',
    textAlign: 'center',
    fontFamily: 'Rubik-Bold',
    color: Color.textBase,
    fontSize: 22,
    marginTop: 30,
  },
  card: {
    width: '100%',
    borderRadius: 9,
    backgroundColor: Color.bg1,
    padding: 20,
    marginTop: 20,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 1.24,

    elevation: 5,
  },
  userData: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  fio: {
    marginLeft: 20,
    color: '#000',
    fontFamily: 'Rubik-Bold',
    fontSize: 17,
    width: '78%',
  },
  info: {
    marginTop: 20,
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '90%',
  },
  infoItem: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    width: '100%',
    marginBottom: 10,
  },
  top10: {
    marginTop: 5,
  },
  placeHolder: {
    color: Color.placeHolder,
    marginBottom: 5,
    fontFamily: 'Rubik-Regular',
  },
  infoItemText: {
    color: Color.textBase,
    fontFamily: 'Rubik-Regular',
    fontSize: 16,
  },
  block: {
    width: '40%',
  },
  sendError: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginVertical: 20,
  },
  borderSendError: {
    borderBottomColor: Color.textError,
    borderBottomWidth: 1,
    marginLeft: 10,
  },
  sendErrorText: {
    color: Color.textError,
    fontFamily: 'Rubik-Regular',
  },
  changeBtn: {
    backgroundColor: Color.bg3,
    marginBottom: 20,
  },
  currentStatus: {
    color: Color.textBase,
    fontFamily: 'Rubik-Bold',
    fontSize: 17,
    marginBottom: 5,
  },
  days: {
    color: Color.placeHolder,
    fontFamily: 'Rubik-Regular',
  },
  secondCard: {
    width: '100%',
    borderRadius: 9,
    backgroundColor: Color.bg1,
    padding: 20,
    marginTop: 20,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 1.24,
    flexDirection: 'row',
    elevation: 5,
    alignItems: 'center',
  },
  status: {
    backgroundColor: '#CBFFB3',
    borderRadius: 100,
    padding: 8,
    paddingHorizontal: 10,
    marginLeft: 20,
  },
  statusText: {
    color: '#43B70D',
    fontFamily: 'Rubik-Regular',
    marginTop: -2,
  },
  bunus: {
    fontFamily: 'Rubik-Regular',
    color: Color.textBase,
    fontSize: 15,
  },
  content: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
  },
  smallCard: {
    width: '48%',
    borderRadius: 9,
    backgroundColor: Color.bg1,
    padding: 20,
    marginTop: 20,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 1.24,
    elevation: 5,
    height: 100,
    justifyContent: 'center',
  },
  smallCard2: {
    width: '48.5%',
    borderRadius: 9,
    backgroundColor: Color.bg1,
    padding: 20,
    marginTop: 20,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 1.24,
    elevation: 5,
    height: 100,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  balance: {
    color: Color.textError,
    fontSize: 24,
    fontFamily: 'Rubik-Regular',
    flexDirection: 'row',
  },
  little: {
    fontSize: 14,
    fontFamily: 'Rubik-Regular',
  },
  more: {
    color: Color.textError,
    fontFamily: 'Rubik-Regular',
  },
  border: {
    borderBottomColor: Color.textError,
    borderBottomWidth: 1,
  },
  redPrice: {
    color: Color.textError,
    fontFamily: 'Rubik-Regular',
    fontSize: 16,
    marginTop: 5,
  },
  nextPayInfo: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 5,
  },
  mainlyBtn: {
    backgroundColor: Color.bg3,
    marginTop: 20,
    marginBottom: 5,
  },
  secondlyBtn: {
    backgroundColor: Color.bg1,
    borderColor: Color.textError,
    borderWidth: 2,
    marginTop: 5,
  },
  tariffName: {
    color: Color.textBase,
    fontFamily: 'Rubik-Bold',
    textAlign: 'center',
    fontSize: 24,
  },
  mainSpeed: {
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 20,
  },
  mainSpeedText: {
    fontFamily: 'Rubik-Regular',
    color: Color.textBase,
    fontSize: 80,
  },
  speed: {
    fontSize: 20,
    fontFamily: 'Rubik-Regular',
  },
  mainSpeedDesc: {
    marginTop: -25,
    fontFamily: 'Rubik-Regular',
    color: '#757575',
    marginBottom: 20,
  },
  listSpeed: {
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    width: '100%',
    flexDirection: 'row',
  },
  itemSpeed: {
    width: '45%',
    marginTop: 5,
  },
  itemSpeedBig: {
    marginTop: 5,
    width: '100%',
  },
  itemSpeedPlaceholder: {
    color: '#757575',
    fontFamily: 'Rubik-Regular',
    marginBottom: 5,
  },
  monthFee: {
    color: '#F35459',
    fontFamily: 'Rubik-Medium',
    fontSize: 17,
  },
  itemSpeedText: {
    fontSize: 17,
    fontFamily: 'Rubik-Regular',
  },
  descSpeed: {
    textAlign: 'center',
    paddingHorizontal: 20,
    marginTop: 20,
    fontFamily: 'Rubik-Regular',
    color: Color.placeHolder,
  },
});
